# Generated by Django 3.2.5 on 2021-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalEfficacyTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechnicalEfficacy', models.CharField(max_length=30, null=True)),
                ('year', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
                ('DeleteStatus', models.IntegerField(null=True)),
            ],
        ),
    ]
