# Generated by Django 3.2.5 on 2021-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentsTrendOverYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateType', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('patentType', models.CharField(max_length=30, null=True)),
                ('DeleteStatus', models.IntegerField(null=True)),
            ],
        ),
    ]
