# Generated by Django 3.2.5 on 2021-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_analysis', '0002_patentstrendoveryears'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenYearMonthDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30, null=True)),
                ('PatentType', models.CharField(max_length=30, null=True)),
                ('DeleteStatus', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatentLifeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LifeCycleType', models.CharField(max_length=30, null=True)),
                ('ApplyTime', models.CharField(max_length=30, null=True)),
                ('ApplicantsNumber', models.IntegerField(null=True)),
                ('PatentNumber', models.IntegerField(null=True)),
                ('DeleteStatus', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='patentstrendoveryears',
            old_name='dateType',
            new_name='DateType',
        ),
        migrations.RenameField(
            model_name='patentstrendoveryears',
            old_name='patentType',
            new_name='PatentType',
        ),
    ]
